name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install asdf plugin
        run: asdf plugin add ticgit "${{ github.workspace }}"

      - name: List all versions
        run: asdf list all ticgit

      - name: Install latest ticgit
        run: |
          asdf install ticgit latest
          asdf global ticgit latest

      - name: Verify installation
        run: ti --version
